### ISSUE TITLE
New Message Indicator broken on Web App

### ISSUE THREAD

**Issue by arnehorn** [be-gosu/issues#129] opened 2015-08-16 16:17 UTC

**Comment by maddrag0n** [comment] 2015-08-17 06:29
@arnehorn please elaborate

**Comment by arnehorn** [comment] 2015-08-17 07:29
thx @maddrag0n for the hinweising on issue reporting guidelines :)

regarding the issue: I just get randomly New Message Indicator - sometimes I get it in channels like #members but in not that crowded channels I don't get them every time

**Comment by maddrag0n** [comment] 2015-08-17 07:31
duplicate of https://github.com/be-gosu/issues/issues/94

**Comment by arnehorn** [comment] 2015-08-17 07:31
k

**Closed by maddrag0n** 2015-08-17 07:31 UTC
Labels: bug, duplicate, web client
